// ====================================================================
// EN PROFILE — Central Data-Driven Asset Catalog
// Zero-Cost Static Architecture: SVGs in /public/assets/
// ====================================================================
import { ProfileAsset, EquippedCosmetics, UserProfileState } from "./types";

export const ASSET_CATALOG: ProfileAsset[] = [
  // ------------------------------------------------------------------
  // 1. AVATAR FRAMES
  // ------------------------------------------------------------------
  {
    id: "frame_avatar_where_winds_meet",
    category: "avatar_frame",
    name: "Where Winds Meet Avatar Frame",
    description: "Thunder lion crowned crest with ceremonial bells, tassels, and high-voltage storm plasma.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_avatar_frame.png",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_avatar_frame.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "where_winds_meet", is_full_canvas: true },
  },
  {
    id: "frame_avatar_palworld",
    category: "avatar_frame",
    name: "Palworld Electric Bunny Frame",
    description: "Golden robotic beast ring crowned by an electric bunny and woolly Lamball guardian.",
    asset_url: "/assets/themes/palworld/palworld_avatar_frame.png",
    preview_url: "/assets/themes/palworld/palworld_avatar_frame_crop.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "palworld", is_full_canvas: true },
  },
  {
    id: "frame_avatar_vault_seeker",
    category: "avatar_frame",
    name: "Violet Seeker Crest",
    description: "Ornate glowing violet frame with top and bottom crest gems.",
    asset_url: "/assets/frames/avatar_vault_seeker.svg",
    preview_url: "/assets/frames/avatar_vault_seeker.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 100 },
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_avatar_flame",
    category: "avatar_frame",
    name: "Solar Corona Ring",
    description: "Blazing solar crest avatar frame with golden rays.",
    asset_url: "/assets/frames/avatar_flame.svg",
    preview_url: "/assets/frames/avatar_flame.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 150 },
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "gold" },
  },
  {
    id: "frame_avatar_crimson",
    category: "avatar_frame",
    name: "Crimson Blaze Ring",
    description: "Volcanic crimson plasma avatar frame.",
    asset_url: "/assets/frames/avatar_crimson.svg",
    preview_url: "/assets/frames/avatar_crimson.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 200 },
    is_starter: true,
    rarity: "epic",
    metadata: { theme: "crimson" },
  },
  {
    id: "frame_avatar_emerald",
    category: "avatar_frame",
    name: "Emerald Matrix Ring",
    description: "Radiant emerald cybernetic frame.",
    asset_url: "/assets/frames/avatar_emerald.svg",
    preview_url: "/assets/frames/avatar_emerald.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 200 },
    is_starter: true,
    rarity: "epic",
    metadata: { theme: "emerald" },
  },
  {
    id: "frame_avatar_quantum",
    category: "avatar_frame",
    name: "Quantum Cyber Halo",
    description: "Rotating holographic glyphs surrounding the avatar.",
    asset_url: "/assets/frames/avatar_quantum.svg",
    preview_url: "/assets/frames/avatar_quantum.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 250 },
    is_starter: true,
    rarity: "legendary",
    metadata: { theme: "quantum" },
  },
  {
    id: "frame_avatar_crown",
    category: "avatar_frame",
    name: "Imperial Crown",
    description: "Ornate crystalline crown for veteran guild champions.",
    asset_url: "/assets/frames/avatar_crown.svg",
    preview_url: "/assets/frames/avatar_crown.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 300 },
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "imperial" },
  },
  {
    id: "frame_avatar_silver",
    category: "avatar_frame",
    name: "Silver Core Ring",
    description: "Sleek brushed aluminum circular avatar frame.",
    asset_url: "/assets/frames/avatar_silver.svg",
    preview_url: "/assets/frames/avatar_silver.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 400 },
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "silver" },
  },
  {
    id: "frame_avatar_violet",
    category: "avatar_frame",
    name: "Violet Arc Reactor",
    description: "Charged electro-plasma avatar frame with lightning prongs.",
    asset_url: "/assets/frames/avatar_violet.svg",
    preview_url: "/assets/frames/avatar_violet.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 500 },
    is_starter: true,
    rarity: "epic",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_avatar_celestial",
    category: "avatar_frame",
    name: "Celestial Corona",
    description: "Starlight woven into an ethereal boundary.",
    asset_url: "/assets/frames/avatar_flame.svg",
    preview_url: "/assets/frames/avatar_flame.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 750 },
    is_starter: true,
    rarity: "legendary",
    metadata: { theme: "celestial" },
  },
  {
    id: "frame_avatar_obsidian",
    category: "avatar_frame",
    name: "Obsidian Halo",
    description: "Dark matter forged into a ring of power.",
    asset_url: "/assets/frames/avatar_crown.svg",
    preview_url: "/assets/frames/avatar_crown.svg",
    unlock_type: "vault_coins",
    unlock_req: { vault_coins_cost: 1000 },
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "obsidian" },
  },

  // ------------------------------------------------------------------
  // 2. CARD FRAMES (1200 x 675 px outer borders)
  // ------------------------------------------------------------------
  {
    id: "frame_card_where_winds_meet",
    category: "card_frame",
    name: "Where Winds Meet Card Frame",
    description: "Ornate Eastern battle border with thunder lion beast, Fengyi banner, and pagoda crests.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_profile_frame.png",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_profile_frame.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "where_winds_meet", is_full_canvas: true },
  },
  {
    id: "frame_card_palworld",
    category: "card_frame",
    name: "Palworld Frontier Border",
    description: "Leafy mechanical frontier border adorned with golden banners and totem crests.",
    asset_url: "/assets/themes/palworld/palworld_card_frame.png",
    preview_url: "/assets/themes/palworld/palworld_card_frame.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { theme: "palworld", is_full_canvas: true },
  },
  {
    id: "frame_card_vault_legendary",
    category: "card_frame",
    name: "Vault Sovereign Ornate Frame",
    description: "Golden and violet crystalline beveled frame with sharp ornate corners.",
    asset_url: "/assets/frames/card_vault_legendary.svg",
    preview_url: "/assets/frames/card_vault_legendary.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "legendary",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_card_flame",
    category: "card_frame",
    name: "Golden Solar Frame",
    description: "Radiant solar-forged golden flare border with corner crests.",
    asset_url: "/assets/frames/card_flame.svg",
    preview_url: "/assets/frames/card_flame.svg",
    unlock_type: "level",
    unlock_req: { level: 15 },
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "gold" },
  },
  {
    id: "frame_card_crimson",
    category: "card_frame",
    name: "Crimson Blaze Frame",
    description: "Heavy volcanic crimson energy frame.",
    asset_url: "/assets/frames/card_crimson.svg",
    preview_url: "/assets/frames/card_crimson.svg",
    unlock_type: "level",
    unlock_req: { level: 35 },
    is_starter: true,
    rarity: "epic",
    metadata: { theme: "crimson" },
  },
  {
    id: "frame_card_emerald",
    category: "card_frame",
    name: "Emerald Matrix Frame",
    description: "High-tech emerald cyber conduit border.",
    asset_url: "/assets/frames/card_emerald.svg",
    preview_url: "/assets/frames/card_emerald.svg",
    unlock_type: "level",
    unlock_req: { level: 60 },
    is_starter: true,
    rarity: "epic",
    metadata: { theme: "emerald" },
  },
  {
    id: "frame_card_obsidian",
    category: "card_frame",
    name: "Obsidian Paragon Frame",
    description: "Dark carbon-infused frame with pulsing red core crystals.",
    asset_url: "/assets/frames/card_obsidian.svg",
    preview_url: "/assets/frames/card_obsidian.svg",
    unlock_type: "level",
    unlock_req: { level: 85 },
    is_starter: true,
    rarity: "legendary",
    metadata: { theme: "obsidian" },
  },

  // ------------------------------------------------------------------
  // 3. BACKGROUND THEMES
  // ------------------------------------------------------------------
  {
    id: "theme_where_winds_meet_bg",
    category: "theme_layer",
    name: "Where Winds Meet Storm Battlefield",
    description: "Epic showdown between the solitary swordsman and the colossal thunder storm lion.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_profile_background.jpg",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_profile_background.jpg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { slot: "base", theme: "where_winds_meet" },
  },
  {
    id: "theme_palworld_bg",
    category: "theme_layer",
    name: "Palworld Floating Spires",
    description: "Panoramic vistas of Palpagos Islands with soaring floating towers and untamed wilderness.",
    asset_url: "/assets/themes/palworld/palworld_profile_background.jpg",
    preview_url: "/assets/themes/palworld/palworld_profile_background.jpg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { slot: "base", theme: "palworld" },
  },
  {
    id: "bg_violet_storm",
    category: "theme_layer",
    name: "Violet Storm",
    description: "Dark purple nebula with high-voltage lightning conduits.",
    asset_url: "/assets/themes/bg_violet_storm.svg",
    preview_url: "/assets/themes/bg_violet_storm.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "base", theme: "violet" },
  },
  {
    id: "bg_molten_cavern",
    category: "theme_layer",
    name: "Molten Cavern",
    description: "Deep volcanic obsidian cavern with floating molten embers.",
    asset_url: "/assets/themes/bg_molten_cavern.svg",
    preview_url: "/assets/themes/bg_molten_cavern.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "base", theme: "flame" },
  },
  {
    id: "bg_emerald_grove",
    category: "theme_layer",
    name: "Emerald Grove",
    description: "Mystic glowing emerald bioluminescent canopy.",
    asset_url: "/assets/themes/bg_emerald_grove.svg",
    preview_url: "/assets/themes/bg_emerald_grove.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: true,
    rarity: "epic",
    metadata: { slot: "base", theme: "emerald" },
  },
  {
    id: "bg_deep_chasm",
    category: "theme_layer",
    name: "Deep Chasm",
    description: "Astral abyss with celestial stardust and cyan glow.",
    asset_url: "/assets/themes/bg_deep_chasm.svg",
    preview_url: "/assets/themes/bg_deep_chasm.svg",
    unlock_type: "level",
    unlock_req: { level: 70 },
    is_starter: true,
    rarity: "legendary",
    metadata: { slot: "base", theme: "cyan" },
  },
  {
    id: "bg_solar_flare",
    category: "theme_layer",
    name: "Solar Flare",
    description: "Radiant golden sunburst radiance overlay.",
    asset_url: "/assets/themes/bg_solar_flare.svg",
    preview_url: "/assets/themes/bg_solar_flare.svg",
    unlock_type: "level",
    unlock_req: { level: 90 },
    is_starter: true,
    rarity: "mythic",
    metadata: { slot: "base", theme: "gold" },
  },

  // ------------------------------------------------------------------
  // 4. TITLES
  // ------------------------------------------------------------------
  {
    id: "title_where_winds_meet",
    category: "title",
    name: "Where Winds Meet",
    description: "Ornate purple thunder plaque with roaring lion head and crescent blades.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_title_frame.png",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_title_frame.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { title_text: "WHERE WINDS MEET", color: "#E9D5FF", theme: "where_winds_meet", is_full_canvas: true },
  },
  {
    id: "title_palworld",
    category: "title",
    name: "Palong-palord Wooden Plaque",
    description: "Rustic timber guild banner guarded by twin electric bunny totems.",
    asset_url: "/assets/themes/palworld/palworld_title_frame.png",
    preview_url: "/assets/themes/palworld/palworld_title_crop.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { title_text: "Palong-palord", color: "#FACC15", theme: "palworld", is_full_canvas: true },
  },
  {
    id: "title_vault_seeker",
    category: "title",
    name: "Vault Seeker",
    description: "Seeker of ancient Vault treasures in ENOS.",
    asset_url: "/assets/titles/title_vanguard.svg",
    preview_url: "/assets/titles/title_vanguard.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { title_text: "Vault Seeker", color: "#C084FC" },
  },
  {
    id: "title_elite_member",
    category: "title",
    name: "Elite Member",
    description: "Awarded to distinguished community veterans.",
    asset_url: "/assets/titles/title_pioneer.svg",
    preview_url: "/assets/titles/title_pioneer.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: true,
    rarity: "rare",
    metadata: { title_text: "Elite Member", color: "#F59E0B" },
  },
  {
    id: "title_raid_champion",
    category: "title",
    name: "Raid Champion",
    description: "Forged in weekly ENOS World Boss combat.",
    asset_url: "/assets/titles/title_raider.svg",
    preview_url: "/assets/titles/title_raider.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: true,
    rarity: "epic",
    metadata: { title_text: "Raid Champion", color: "#EF4444" },
  },
  {
    id: "title_guild_master",
    category: "title",
    name: "Guild Master",
    description: "Supreme leader in seasonal Every Nation leaderboards.",
    asset_url: "/assets/titles/title_archon.svg",
    preview_url: "/assets/titles/title_archon.svg",
    unlock_type: "level",
    unlock_req: { level: 75 },
    is_starter: true,
    rarity: "legendary",
    metadata: { title_text: "Guild Master", color: "#10B981" },
  },
  {
    id: "title_eternal_sovereign",
    category: "title",
    name: "Eternal Sovereign",
    description: "The pinnacle title reserved for Level 100 masters.",
    asset_url: "/assets/titles/title_sovereign.svg",
    preview_url: "/assets/titles/title_sovereign.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: true,
    rarity: "mythic",
    metadata: { title_text: "Eternal Sovereign", color: "#FDE68A" },
  },

  // ------------------------------------------------------------------
  // 5. MAIN MILESTONE EMBLEMS
  // ------------------------------------------------------------------
  {
    id: "emblem_where_winds_meet",
    category: "emblem",
    name: "Thunder Lion Medallion",
    description: "Ancient tomoe-crested thunder lion medallion with ceremonial tassels and storm ribbons.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_emblem.png",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_emblem.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { milestone_level: 50, color: "#C084FC", theme: "where_winds_meet" },
  },
  {
    id: "emblem_palworld",
    category: "emblem",
    name: "Palpagos Sun Crest",
    description: "Solar bunny crest awarded to veteran pal tamers.",
    asset_url: "/assets/themes/palworld/palworld_emblem.png",
    preview_url: "/assets/themes/palworld/palworld_emblem.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { milestone_level: 50, color: "#FACC15", theme: "palworld" },
  },
  {
    id: "emblem_starter_silver",
    category: "emblem",
    name: "Initiate Crest",
    description: "Standard Every Nation GG novice member crest.",
    asset_url: "/assets/emblems/emblem_lv1.svg",
    preview_url: "/assets/emblems/emblem_lv1.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { milestone_level: 1, color: "#94A3B8" },
  },
  {
    id: "emblem_milestone_20",
    category: "emblem",
    name: "Iron Vanguard",
    description: "Forged iron crest awarded upon reaching Level 20.",
    asset_url: "/assets/emblems/emblem_lv20.svg",
    preview_url: "/assets/emblems/emblem_lv20.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: true,
    rarity: "rare",
    metadata: { milestone_level: 20, color: "#F59E0B" },
  },
  {
    id: "emblem_milestone_40",
    category: "emblem",
    name: "Silver Archon",
    description: "Radiant twin-blade emblem for Level 40 veterans.",
    asset_url: "/assets/emblems/emblem_lv40.svg",
    preview_url: "/assets/emblems/emblem_lv40.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: true,
    rarity: "epic",
    metadata: { milestone_level: 40, color: "#C084FC" },
  },
  {
    id: "emblem_milestone_60",
    category: "emblem",
    name: "Emerald Reaper",
    description: "High-tier crest honoring master RPG raiders at Level 60.",
    asset_url: "/assets/emblems/emblem_lv60.svg",
    preview_url: "/assets/emblems/emblem_lv60.svg",
    unlock_type: "level",
    unlock_req: { level: 60 },
    is_starter: true,
    rarity: "legendary",
    metadata: { milestone_level: 60, color: "#10B981" },
  },
  {
    id: "emblem_milestone_80",
    category: "emblem",
    name: "Obsidian Paragon",
    description: "Ancient obsidian monolith emblem for Level 80 titans.",
    asset_url: "/assets/emblems/emblem_lv80.svg",
    preview_url: "/assets/emblems/emblem_lv80.svg",
    unlock_type: "level",
    unlock_req: { level: 80 },
    is_starter: true,
    rarity: "legendary",
    metadata: { milestone_level: 80, color: "#EF4444" },
  },
  {
    id: "emblem_milestone_100",
    category: "emblem",
    name: "Celestial Sovereign",
    description: "Ultimate mythic emblem awarded upon achieving Level 100.",
    asset_url: "/assets/emblems/emblem_lv100.svg",
    preview_url: "/assets/emblems/emblem_lv100.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: true,
    rarity: "mythic",
    metadata: { milestone_level: 100, color: "#E0E7FF" },
  },

  // ------------------------------------------------------------------
  // 6. ACHIEVEMENT SHOWCASE BADGES (5 Canonical Showcase Slots)
  // ------------------------------------------------------------------
  {
    id: "badge_where_winds_meet",
    category: "badge",
    name: "Storm Crest",
    description: "Thunder lion crest commemorating victory over the tempest beast.",
    asset_url: "/assets/themes/where_winds_meet/where_winds_meet_achievement_badge.png",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_achievement_badge.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "mythic",
    metadata: { color: "#C084FC", theme: "where_winds_meet" },
  },
  {
    id: "badge_palworld_lamball",
    category: "badge",
    name: "Lamball Pioneer",
    description: "First pal tamed on the frontier.",
    asset_url: "/assets/themes/palworld/palworld_badge_lamball.png",
    preview_url: "/assets/themes/palworld/palworld_badge_lamball.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { color: "#FDE047", theme: "palworld" },
  },
  {
    id: "badge_palworld_bunny",
    category: "badge",
    name: "Electric Spark",
    description: "High voltage pal mastery badge.",
    asset_url: "/assets/themes/palworld/palworld_badge_bunny.png",
    preview_url: "/assets/themes/palworld/palworld_badge_bunny.png",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { color: "#FDE047", theme: "palworld" },
  },
  {
    id: "badge_early_bird",
    category: "badge",
    name: "EARLY BIRD",
    description: "Participate in a daily quest",
    asset_url: "/assets/badges/badge_early_bird.svg",
    preview_url: "/assets/badges/badge_early_bird.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { color: "#C084FC" },
  },
  {
    id: "badge_voice_chatter",
    category: "badge",
    name: "VOICE CHATTER",
    description: "Spend 50 hours in voice channels",
    asset_url: "/assets/badges/badge_voice_chatter.svg",
    preview_url: "/assets/badges/badge_voice_chatter.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { color: "#38BDF8" },
  },
  {
    id: "badge_trivia_master",
    category: "badge",
    name: "TRIVIA MASTER",
    description: "Answer 100 trivia questions correctly",
    asset_url: "/assets/badges/badge_trivia_master.svg",
    preview_url: "/assets/badges/badge_trivia_master.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { color: "#F59E0B" },
  },
  {
    id: "badge_boss_slayer_v2",
    category: "badge",
    name: "BOSS SLAYER",
    description: "Deal 1M damage to world bosses",
    asset_url: "/assets/badges/badge_boss_slayer_v2.svg",
    preview_url: "/assets/badges/badge_boss_slayer_v2.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "epic",
    metadata: { color: "#F43F5E" },
  },
  {
    id: "badge_community_pillar",
    category: "badge",
    name: "COMMUNITY PILLAR",
    description: "Be active for 30 days straight",
    asset_url: "/assets/badges/badge_community_pillar.svg",
    preview_url: "/assets/badges/badge_community_pillar.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "epic",
    metadata: { color: "#10B981" },
  },
  {
    id: "badge_vault_pioneer",
    category: "badge",
    name: "VAULT PIONEER",
    description: "Active Vault Coin staking and community governance.",
    asset_url: "/assets/badges/badge_vault.svg",
    preview_url: "/assets/badges/badge_vault.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { color: "#94A3B8" },
  },
  {
    id: "badge_ap_conqueror",
    category: "badge",
    name: "AP CONQUEROR",
    description: "Maxed out weekly action points 20 weeks in a row.",
    asset_url: "/assets/badges/badge_conqueror.svg",
    preview_url: "/assets/badges/badge_conqueror.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "ap_20" },
    is_starter: true,
    rarity: "legendary",
    metadata: { color: "#EAB308" },
  },
  {
    id: "badge_flawless_streak",
    category: "badge",
    name: "FLAWLESS 365",
    description: "Maintained daily check-ins for 365 days.",
    asset_url: "/assets/badges/badge_streak.svg",
    preview_url: "/assets/badges/badge_streak.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "streak_365" },
    is_starter: true,
    rarity: "mythic",
    metadata: { color: "#F43F5E" },
  },
];

// Helper methods
export function getAssetById(id: string): ProfileAsset | undefined {
  return ASSET_CATALOG.find((a) => a.id === id);
}

export function getAssetsByCategory(category: ProfileAsset["category"]): ProfileAsset[] {
  return ASSET_CATALOG.filter((a) => a.category === category);
}

// Curated Typography Fonts
export const AVAILABLE_FONTS = [
  { id: "Rajdhani", name: "Rajdhani", label: "ABC" },
  { id: "Cinzel", name: "Cinzel", label: "ABC" },
  { id: "Orbitron", name: "Orbitron", label: "ABC" },
  { id: "Outfit", name: "Outfit", label: "ABC" },
  { id: "Montserrat", name: "Montserrat", label: "ABC" },
  { id: "Exo 2", name: "Exo 2", label: "ABC" },
  { id: "Inter", name: "Inter", label: "ABC" },
];

// Curated Swatch Palette matching the reference image row
export const CURATED_COLOR_SWATCHES = [
  { hex: "#FFFFFF", label: "White" },
  { hex: "#F43F5E", label: "Pink" },
  { hex: "#F97316", label: "Orange" },
  { hex: "#EAB308", label: "Yellow" },
  { hex: "#22C55E", label: "Green" },
  { hex: "#06B6D4", label: "Cyan" },
  { hex: "#3B82F6", label: "Blue" },
  { hex: "#A855F7", label: "Violet" },
];

// Combined Profile Frame (Background + Outer Frame in one unified asset)
export interface CombinedProfileFrame {
  id: string;
  name: string;
  description: string;
  preview_url: string;
  bgId: string;
  cardFrameId: string;
  costLabel?: string;
}

export const COMBINED_PROFILE_FRAMES: CombinedProfileFrame[] = [
  {
    id: "profile_frame_where_winds_meet",
    name: "Where Winds Meet",
    description: "Combined Eastern storm lion background and ornate battle frame.",
    preview_url: "/assets/themes/where_winds_meet/where_winds_meet_profile_background.jpg",
    bgId: "theme_where_winds_meet_bg",
    cardFrameId: "frame_card_where_winds_meet",
    costLabel: "None",
  },
  {
    id: "profile_frame_palworld",
    name: "Palworld Frontier",
    description: "Combined Palpagos floating spires background and frontier border.",
    preview_url: "/assets/themes/palworld/palworld_profile_background.jpg",
    bgId: "theme_palworld_bg",
    cardFrameId: "frame_card_palworld",
    costLabel: "None",
  },
  {
    id: "profile_frame_vault_legendary",
    name: "Vault Sovereign",
    description: "Combined violet storm nebula and crystalline golden ornate frame.",
    preview_url: "/assets/themes/bg_violet_storm.svg",
    bgId: "bg_violet_storm",
    cardFrameId: "frame_card_vault_legendary",
    costLabel: "None",
  },
  {
    id: "profile_frame_flame",
    name: "Golden Flame",
    description: "Combined volcanic obsidian cavern and radiant solar frame.",
    preview_url: "/assets/themes/bg_molten_cavern.svg",
    bgId: "bg_molten_cavern",
    cardFrameId: "frame_card_flame",
    costLabel: "None",
  },
  {
    id: "profile_frame_emerald",
    name: "Emerald Matrix",
    description: "Combined glowing emerald canopy and cyber conduit frame.",
    preview_url: "/assets/themes/bg_emerald_grove.svg",
    bgId: "bg_emerald_grove",
    cardFrameId: "frame_card_emerald",
    costLabel: "None",
  },
  {
    id: "profile_frame_obsidian",
    name: "Obsidian Paragon",
    description: "Combined deep astral chasm and dark carbon core frame.",
    preview_url: "/assets/themes/bg_deep_chasm.svg",
    bgId: "bg_deep_chasm",
    cardFrameId: "frame_card_obsidian",
    costLabel: "None",
  },
  {
    id: "profile_frame_solar",
    name: "Solar Sovereign",
    description: "Combined golden solar flare and celestial border.",
    preview_url: "/assets/themes/bg_solar_flare.svg",
    bgId: "bg_solar_flare",
    cardFrameId: "frame_card_celestial",
    costLabel: "None",
  },
];

// All asset IDs from catalog for 100% unlocked testing mode
export const ALL_CATALOG_ASSET_IDS: string[] = ASSET_CATALOG.map((a) => a.id);

// Default Canonical Demo State matching the reference screenshot!
export const DEFAULT_EN_PROFILE: UserProfileState = {
  userId: "891234567890123456",
  guildId: "123456789012345678",
  discordUsername: "EnGG#1234",
  discordDisplayName: "EngG",
  discordAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
  profileExp: 18750,
  profileLevel: 42,
  vaultCoins: 2450,
  equipped: {
    nameFont: "Rajdhani",
    nameColor: "#FFFFFF",
    titleId: "title_vault_seeker",
    titleColor: "#FFFFFF",
    emblemId: "emblem_starter_silver",
    emblemColor: "#C084FC",
    avatarFrameId: "frame_avatar_vault_seeker",
    cardFrameId: "frame_card_vault_legendary",
    themeLayers: ["bg_violet_storm"],
    coinColor: "#F59E0B",
    achievementSlots: [
      "badge_early_bird",
      "badge_voice_chatter",
      "badge_trivia_master",
      "badge_boss_slayer_v2",
      "badge_community_pillar",
    ],
  },
  unlockedAssetIds: ALL_CATALOG_ASSET_IDS,
};

export const STARTER_IDENTITIES = {
  silver: DEFAULT_EN_PROFILE.equipped,
  violet: DEFAULT_EN_PROFILE.equipped,
  flame: {
    ...DEFAULT_EN_PROFILE.equipped,
    avatarFrameId: "frame_avatar_flame",
    cardFrameId: "frame_card_flame",
    themeLayers: ["bg_molten_cavern"],
    titleColor: "#F59E0B",
    coinColor: "#F59E0B",
  },
};

export const DEMO_PROFILES: Record<string, UserProfileState> = {
  where_winds_meet: {
    ...DEFAULT_EN_PROFILE,
    userId: "918273645544332211",
    discordUsername: "WindsMeet#0001",
    discordDisplayName: "燕云十六声",
    profileLevel: 99,
    profileExp: 417143,
    vaultCoins: 9999,
    equipped: {
      nameFont: "Cinzel",
      nameColor: "#FFFFFF",
      titleId: "title_where_winds_meet",
      titleColor: "#E9D5FF",
      emblemId: "emblem_where_winds_meet",
      emblemColor: "#C084FC",
      avatarFrameId: "frame_avatar_where_winds_meet",
      cardFrameId: "frame_card_where_winds_meet",
      themeLayers: ["theme_where_winds_meet_bg"],
      coinColor: "#DDD6FE",
      achievementSlots: [
        "badge_where_winds_meet",
        "badge_where_winds_meet",
        "badge_where_winds_meet",
        "badge_where_winds_meet",
        "badge_where_winds_meet",
      ],
    },
    unlockedAssetIds: ALL_CATALOG_ASSET_IDS,
  },
  veteran: DEFAULT_EN_PROFILE,
  palworld: {
    ...DEFAULT_EN_PROFILE,
    userId: "776655443322110099",
    discordUsername: "PalTamer#0001",
    discordDisplayName: "Palong-palord",
    profileLevel: 65,
    profileExp: 245000,
    vaultCoins: 8500,
    equipped: {
      nameFont: "Rajdhani",
      nameColor: "#FDE047",
      titleId: "title_palworld",
      titleColor: "#FACC15",
      emblemId: "emblem_palworld",
      emblemColor: "#FACC15",
      avatarFrameId: "frame_avatar_palworld",
      cardFrameId: "frame_card_palworld",
      themeLayers: ["theme_palworld_bg"],
      coinColor: "#FDE047",
      achievementSlots: [
        "badge_palworld_lamball",
        "badge_palworld_bunny",
        "badge_palworld_lamball",
        "badge_palworld_bunny",
        "badge_palworld_lamball",
      ],
    },
    unlockedAssetIds: ALL_CATALOG_ASSET_IDS,
  },
  raider_violet: {
    ...DEFAULT_EN_PROFILE,
    userId: "782345678901234567",
    discordUsername: "Valkyrie#5678",
    discordDisplayName: "⚡ Valkyrie ⚡",
    profileLevel: 52,
    profileExp: 168000,
    vaultCoins: 12450,
  },
  mythic_sovereign: {
    ...DEFAULT_EN_PROFILE,
    userId: "993456789012345678",
    discordUsername: "SolInvictus#9999",
    discordDisplayName: "✦ Sol Invictus ✦",
    profileLevel: 100,
    profileExp: 417143,
    vaultCoins: 99999,
  },
};



