// ====================================================================
// EN PROFILE — Central Data-Driven Asset Catalog
// Zero-Cost Static Architecture: SVGs in /public/assets/
// ====================================================================
import { ProfileAsset, EquippedCosmetics, UserProfileState } from "./types";

export const ASSET_CATALOG: ProfileAsset[] = [
  // ------------------------------------------------------------------
  // 1. AVATAR FRAMES
  // ------------------------------------------------------------------
  {
    id: "frame_avatar_vault_seeker",
    category: "avatar_frame",
    name: "Violet Seeker Crest",
    description: "Ornate glowing violet frame with top and bottom crest gems.",
    asset_url: "/assets/frames/avatar_vault_seeker.svg",
    preview_url: "/assets/frames/avatar_vault_seeker.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_avatar_flame",
    category: "avatar_frame",
    name: "Solar Corona Ring",
    description: "Blazing solar crest avatar frame with golden rays.",
    asset_url: "/assets/frames/avatar_flame.svg",
    preview_url: "/assets/frames/avatar_flame.svg",
    unlock_type: "level",
    unlock_req: { level: 10 },
    is_starter: false,
    rarity: "rare",
    metadata: { theme: "gold" },
  },
  {
    id: "frame_avatar_crimson",
    category: "avatar_frame",
    name: "Crimson Blaze Ring",
    description: "Volcanic crimson plasma avatar frame.",
    asset_url: "/assets/frames/avatar_crimson.svg",
    preview_url: "/assets/frames/avatar_crimson.svg",
    unlock_type: "level",
    unlock_req: { level: 25 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "crimson" },
  },
  {
    id: "frame_avatar_emerald",
    category: "avatar_frame",
    name: "Emerald Matrix Ring",
    description: "Radiant emerald cybernetic frame.",
    asset_url: "/assets/frames/avatar_emerald.svg",
    preview_url: "/assets/frames/avatar_emerald.svg",
    unlock_type: "level",
    unlock_req: { level: 50 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "emerald" },
  },
  {
    id: "frame_avatar_quantum",
    category: "avatar_frame",
    name: "Quantum Cyber Halo",
    description: "Rotating holographic glyphs surrounding the avatar.",
    asset_url: "/assets/frames/avatar_quantum.svg",
    preview_url: "/assets/frames/avatar_quantum.svg",
    unlock_type: "level",
    unlock_req: { level: 75 },
    is_starter: false,
    rarity: "legendary",
    metadata: { theme: "quantum" },
  },
  {
    id: "frame_avatar_crown",
    category: "avatar_frame",
    name: "Imperial Crown",
    description: "Ornate crystalline crown for veteran guild champions.",
    asset_url: "/assets/frames/avatar_crown.svg",
    preview_url: "/assets/frames/avatar_crown.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { theme: "imperial" },
  },

  // ------------------------------------------------------------------
  // 2. CARD FRAMES (1200 x 675 px outer borders)
  // ------------------------------------------------------------------
  {
    id: "frame_card_vault_legendary",
    category: "card_frame",
    name: "Vault Sovereign Ornate Frame",
    description: "Golden and violet crystalline beveled frame with sharp ornate corners.",
    asset_url: "/assets/frames/card_vault_legendary.svg",
    preview_url: "/assets/frames/card_vault_legendary.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "legendary",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_card_flame",
    category: "card_frame",
    name: "Golden Solar Frame",
    description: "Radiant solar-forged golden flare border with corner crests.",
    asset_url: "/assets/frames/card_flame.svg",
    preview_url: "/assets/frames/card_flame.svg",
    unlock_type: "level",
    unlock_req: { level: 15 },
    is_starter: false,
    rarity: "rare",
    metadata: { theme: "gold" },
  },
  {
    id: "frame_card_crimson",
    category: "card_frame",
    name: "Crimson Blaze Frame",
    description: "Heavy volcanic crimson energy frame.",
    asset_url: "/assets/frames/card_crimson.svg",
    preview_url: "/assets/frames/card_crimson.svg",
    unlock_type: "level",
    unlock_req: { level: 35 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "crimson" },
  },
  {
    id: "frame_card_emerald",
    category: "card_frame",
    name: "Emerald Matrix Frame",
    description: "High-tech emerald cyber conduit border.",
    asset_url: "/assets/frames/card_emerald.svg",
    preview_url: "/assets/frames/card_emerald.svg",
    unlock_type: "level",
    unlock_req: { level: 60 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "emerald" },
  },
  {
    id: "frame_card_obsidian",
    category: "card_frame",
    name: "Obsidian Paragon Frame",
    description: "Dark carbon-infused frame with pulsing red core crystals.",
    asset_url: "/assets/frames/card_obsidian.svg",
    preview_url: "/assets/frames/card_obsidian.svg",
    unlock_type: "level",
    unlock_req: { level: 85 },
    is_starter: false,
    rarity: "legendary",
    metadata: { theme: "obsidian" },
  },

  // ------------------------------------------------------------------
  // 3. BACKGROUND THEMES
  // ------------------------------------------------------------------
  {
    id: "bg_violet_storm",
    category: "theme_layer",
    name: "Violet Storm",
    description: "Dark purple nebula with high-voltage lightning conduits.",
    asset_url: "/assets/themes/bg_violet_storm.svg",
    preview_url: "/assets/themes/bg_violet_storm.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "base", theme: "violet" },
  },
  {
    id: "bg_molten_cavern",
    category: "theme_layer",
    name: "Molten Cavern",
    description: "Deep volcanic obsidian cavern with floating molten embers.",
    asset_url: "/assets/themes/bg_molten_cavern.svg",
    preview_url: "/assets/themes/bg_molten_cavern.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: false,
    rarity: "rare",
    metadata: { slot: "base", theme: "flame" },
  },
  {
    id: "bg_emerald_grove",
    category: "theme_layer",
    name: "Emerald Grove",
    description: "Mystic glowing emerald bioluminescent canopy.",
    asset_url: "/assets/themes/bg_emerald_grove.svg",
    preview_url: "/assets/themes/bg_emerald_grove.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: false,
    rarity: "epic",
    metadata: { slot: "base", theme: "emerald" },
  },
  {
    id: "bg_deep_chasm",
    category: "theme_layer",
    name: "Deep Chasm",
    description: "Astral abyss with celestial stardust and cyan glow.",
    asset_url: "/assets/themes/bg_deep_chasm.svg",
    preview_url: "/assets/themes/bg_deep_chasm.svg",
    unlock_type: "level",
    unlock_req: { level: 70 },
    is_starter: false,
    rarity: "legendary",
    metadata: { slot: "base", theme: "cyan" },
  },
  {
    id: "bg_solar_flare",
    category: "theme_layer",
    name: "Solar Flare",
    description: "Radiant golden sunburst radiance overlay.",
    asset_url: "/assets/themes/bg_solar_flare.svg",
    preview_url: "/assets/themes/bg_solar_flare.svg",
    unlock_type: "level",
    unlock_req: { level: 90 },
    is_starter: false,
    rarity: "mythic",
    metadata: { slot: "base", theme: "gold" },
  },

  // ------------------------------------------------------------------
  // 4. TITLES
  // ------------------------------------------------------------------
  {
    id: "title_vault_seeker",
    category: "title",
    name: "Vault Seeker",
    description: "Seeker of ancient Vault treasures in ENOS.",
    asset_url: "/assets/titles/title_vanguard.svg",
    preview_url: "/assets/titles/title_vanguard.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { title_text: "Vault Seeker", color: "#C084FC" },
  },
  {
    id: "title_elite_member",
    category: "title",
    name: "Elite Member",
    description: "Awarded to distinguished community veterans.",
    asset_url: "/assets/titles/title_pioneer.svg",
    preview_url: "/assets/titles/title_pioneer.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: false,
    rarity: "rare",
    metadata: { title_text: "Elite Member", color: "#F59E0B" },
  },
  {
    id: "title_raid_champion",
    category: "title",
    name: "Raid Champion",
    description: "Forged in weekly ENOS World Boss combat.",
    asset_url: "/assets/titles/title_raider.svg",
    preview_url: "/assets/titles/title_raider.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: false,
    rarity: "epic",
    metadata: { title_text: "Raid Champion", color: "#EF4444" },
  },
  {
    id: "title_guild_master",
    category: "title",
    name: "Guild Master",
    description: "Supreme leader in seasonal Every Nation leaderboards.",
    asset_url: "/assets/titles/title_archon.svg",
    preview_url: "/assets/titles/title_archon.svg",
    unlock_type: "level",
    unlock_req: { level: 75 },
    is_starter: false,
    rarity: "legendary",
    metadata: { title_text: "Guild Master", color: "#10B981" },
  },
  {
    id: "title_eternal_sovereign",
    category: "title",
    name: "Eternal Sovereign",
    description: "The pinnacle title reserved for Level 100 masters.",
    asset_url: "/assets/titles/title_sovereign.svg",
    preview_url: "/assets/titles/title_sovereign.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { title_text: "Eternal Sovereign", color: "#FDE68A" },
  },

  // ------------------------------------------------------------------
  // 5. MAIN MILESTONE EMBLEMS
  // ------------------------------------------------------------------
  {
    id: "emblem_starter_silver",
    category: "emblem",
    name: "Initiate Crest",
    description: "Standard Every Nation GG novice member crest.",
    asset_url: "/assets/emblems/emblem_lv1.svg",
    preview_url: "/assets/emblems/emblem_lv1.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { milestone_level: 1, color: "#94A3B8" },
  },
  {
    id: "emblem_milestone_20",
    category: "emblem",
    name: "Iron Vanguard",
    description: "Forged iron crest awarded upon reaching Level 20.",
    asset_url: "/assets/emblems/emblem_lv20.svg",
    preview_url: "/assets/emblems/emblem_lv20.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: false,
    rarity: "rare",
    metadata: { milestone_level: 20, color: "#F59E0B" },
  },
  {
    id: "emblem_milestone_40",
    category: "emblem",
    name: "Silver Archon",
    description: "Radiant twin-blade emblem for Level 40 veterans.",
    asset_url: "/assets/emblems/emblem_lv40.svg",
    preview_url: "/assets/emblems/emblem_lv40.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: false,
    rarity: "epic",
    metadata: { milestone_level: 40, color: "#C084FC" },
  },
  {
    id: "emblem_milestone_60",
    category: "emblem",
    name: "Emerald Reaper",
    description: "High-tier crest honoring master RPG raiders at Level 60.",
    asset_url: "/assets/emblems/emblem_lv60.svg",
    preview_url: "/assets/emblems/emblem_lv60.svg",
    unlock_type: "level",
    unlock_req: { level: 60 },
    is_starter: false,
    rarity: "legendary",
    metadata: { milestone_level: 60, color: "#10B981" },
  },
  {
    id: "emblem_milestone_80",
    category: "emblem",
    name: "Obsidian Paragon",
    description: "Ancient obsidian monolith emblem for Level 80 titans.",
    asset_url: "/assets/emblems/emblem_lv80.svg",
    preview_url: "/assets/emblems/emblem_lv80.svg",
    unlock_type: "level",
    unlock_req: { level: 80 },
    is_starter: false,
    rarity: "legendary",
    metadata: { milestone_level: 80, color: "#EF4444" },
  },
  {
    id: "emblem_milestone_100",
    category: "emblem",
    name: "Celestial Sovereign",
    description: "Ultimate mythic emblem awarded upon achieving Level 100.",
    asset_url: "/assets/emblems/emblem_lv100.svg",
    preview_url: "/assets/emblems/emblem_lv100.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { milestone_level: 100, color: "#E0E7FF" },
  },

  // ------------------------------------------------------------------
  // 6. ACHIEVEMENT SHOWCASE BADGES (5 Slots)
  // ------------------------------------------------------------------
  {
    id: "badge_boss_slayer",
    category: "badge",
    name: "World Boss Slayer",
    description: "Participated in weekly ENOS World Boss battles.",
    asset_url: "/assets/badges/badge_boss.svg",
    preview_url: "/assets/badges/badge_boss.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "skull" },
  },
  {
    id: "badge_vault_pioneer",
    category: "badge",
    name: "Vault Pioneer",
    description: "Active Vault Coin staking and community governance.",
    asset_url: "/assets/badges/badge_vault.svg",
    preview_url: "/assets/badges/badge_vault.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { icon: "coins" },
  },
  {
    id: "badge_quest_master",
    category: "badge",
    name: "Quest Master",
    description: "Completed Daily Quests in Every Nation GG.",
    asset_url: "/assets/badges/badge_quest.svg",
    preview_url: "/assets/badges/badge_quest.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "compass" },
  },
  {
    id: "badge_trivia_sage",
    category: "badge",
    name: "Trivia Sage",
    description: "Proved intellect in Daily Community Trivia.",
    asset_url: "/assets/badges/badge_trivia.svg",
    preview_url: "/assets/badges/badge_trivia.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "brain" },
  },
  {
    id: "badge_guild_champion",
    category: "badge",
    name: "Guild Champion",
    description: "Top contributor in Every Nation GG leaderboards.",
    asset_url: "/assets/badges/badge_guild.svg",
    preview_url: "/assets/badges/badge_guild.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "epic",
    metadata: { icon: "trophy" },
  },
  {
    id: "badge_ap_conqueror",
    category: "badge",
    name: "AP Conqueror",
    description: "Maxed out weekly action points 20 weeks in a row.",
    asset_url: "/assets/badges/badge_conqueror.svg",
    preview_url: "/assets/badges/badge_conqueror.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "ap_20" },
    is_starter: false,
    rarity: "legendary",
    metadata: { icon: "zap" },
  },
  {
    id: "badge_flawless_streak",
    category: "badge",
    name: "Flawless 365 Streak",
    description: "Maintained daily check-ins for 365 days.",
    asset_url: "/assets/badges/badge_streak.svg",
    preview_url: "/assets/badges/badge_streak.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "streak_365" },
    is_starter: false,
    rarity: "mythic",
    metadata: { icon: "flame" },
  },
];

// Helper methods
export function getAssetById(id: string): ProfileAsset | undefined {
  return ASSET_CATALOG.find((a) => a.id === id);
}

export function getAssetsByCategory(category: ProfileAsset["category"]): ProfileAsset[] {
  return ASSET_CATALOG.filter((a) => a.category === category);
}

// Curated Typography Fonts
export const AVAILABLE_FONTS = [
  { id: "Rajdhani", name: "Rajdhani", label: "ABC" },
  { id: "Cinzel", name: "Cinzel", label: "ABC" },
  { id: "Orbitron", name: "Orbitron", label: "ABC" },
  { id: "Outfit", name: "Outfit", label: "ABC" },
  { id: "Montserrat", name: "Montserrat", label: "ABC" },
  { id: "Exo 2", name: "Exo 2", label: "ABC" },
  { id: "Inter", name: "Inter", label: "ABC" },
];

// Curated Swatch Palette matching the reference image row
export const CURATED_COLOR_SWATCHES = [
  { hex: "#FFFFFF", label: "White" },
  { hex: "#F43F5E", label: "Pink" },
  { hex: "#F97316", label: "Orange" },
  { hex: "#EAB308", label: "Yellow" },
  { hex: "#22C55E", label: "Green" },
  { hex: "#06B6D4", label: "Cyan" },
  { hex: "#3B82F6", label: "Blue" },
  { hex: "#A855F7", label: "Violet" },
];

// Default Canonical Demo State matching the reference screenshot!
export const DEFAULT_EN_PROFILE: UserProfileState = {
  userId: "891234567890123456",
  guildId: "123456789012345678",
  discordUsername: "EnGG#1234",
  discordDisplayName: "EnGG",
  discordAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
  profileExp: 18750,
  profileLevel: 42,
  vaultCoins: 2450,
  equipped: {
    nameFont: "Rajdhani",
    nameColor: "#FFFFFF",
    titleId: "title_vault_seeker",
    titleColor: "#C084FC",
    emblemId: "emblem_milestone_40",
    emblemColor: "#C084FC",
    avatarFrameId: "frame_avatar_vault_seeker",
    cardFrameId: "frame_card_vault_legendary",
    themeLayers: ["bg_violet_storm"],
    coinColor: "#F59E0B",
    achievementSlots: [
      "emblem_milestone_40",
      "badge_quest_master",
      "badge_guild_champion",
      "badge_boss_slayer",
      "badge_vault_pioneer",
    ],
  },
  unlockedAssetIds: [
    "frame_avatar_vault_seeker",
    "frame_card_vault_legendary",
    "bg_violet_storm",
    "title_vault_seeker",
    "emblem_starter_silver",
    "emblem_milestone_20",
    "emblem_milestone_40",
    "badge_boss_slayer",
    "badge_vault_pioneer",
    "badge_quest_master",
    "badge_trivia_sage",
    "badge_guild_champion",
  ],
};

export const STARTER_IDENTITIES = {
  silver: DEFAULT_EN_PROFILE.equipped,
  violet: DEFAULT_EN_PROFILE.equipped,
  flame: {
    ...DEFAULT_EN_PROFILE.equipped,
    avatarFrameId: "frame_avatar_flame",
    cardFrameId: "frame_card_flame",
    themeLayers: ["bg_molten_cavern"],
    titleColor: "#F59E0B",
    coinColor: "#F59E0B",
  },
};

export const DEMO_PROFILES: Record<string, UserProfileState> = {
  veteran: DEFAULT_EN_PROFILE,
  raider_violet: {
    ...DEFAULT_EN_PROFILE,
    userId: "782345678901234567",
    discordUsername: "Valkyrie#5678",
    discordDisplayName: "⚡ Valkyrie ⚡",
    profileLevel: 52,
    profileExp: 168000,
    vaultCoins: 12450,
  },
  mythic_sovereign: {
    ...DEFAULT_EN_PROFILE,
    userId: "993456789012345678",
    discordUsername: "SolInvictus#9999",
    discordDisplayName: "✦ Sol Invictus ✦",
    profileLevel: 100,
    profileExp: 417143,
    vaultCoins: 99999,
  },
};


