// ====================================================================
// EN PROFILE — Central Data-Driven Asset Catalog
// Zero-Cost Static Architecture: SVGs in /public/assets/
// ====================================================================
import { ProfileAsset, EquippedCosmetics, UserProfileState } from "./types";

export const ASSET_CATALOG: ProfileAsset[] = [
  // ------------------------------------------------------------------
  // 1. CARD FRAMES (1200 x 675 px outer borders)
  // ------------------------------------------------------------------
  {
    id: "frame_card_silver",
    category: "card_frame",
    name: "Silver Aegis Frame",
    description: "Clean minimalist metallic chrome border with edge bevels.",
    asset_url: "/assets/frames/card_silver.svg",
    preview_url: "/assets/frames/card_silver.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { theme: "silver" },
  },
  {
    id: "frame_card_violet",
    category: "card_frame",
    name: "Electric Violet Matrix Frame",
    description: "High-voltage neon violet energy conduit border.",
    asset_url: "/assets/frames/card_violet.svg",
    preview_url: "/assets/frames/card_violet.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_card_flame",
    category: "card_frame",
    name: "Flaming Golden Solar Frame",
    description: "Radiant solar-forged golden flare border with corner crests.",
    asset_url: "/assets/frames/card_flame.svg",
    preview_url: "/assets/frames/card_flame.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "flame" },
  },
  {
    id: "frame_card_obsidian",
    category: "card_frame",
    name: "Obsidian Paragon Frame",
    description: "Dark carbon-infused frame with pulsing red core crystals.",
    asset_url: "/assets/frames/card_obsidian.svg",
    preview_url: "/assets/frames/card_obsidian.svg",
    unlock_type: "level",
    unlock_req: { level: 50 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "obsidian" },
  },
  {
    id: "frame_card_celestial",
    category: "card_frame",
    name: "Celestial Sovereign Frame",
    description: "Mythic astral halo frame with prismatic diamond accents.",
    asset_url: "/assets/frames/card_celestial.svg",
    preview_url: "/assets/frames/card_celestial.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { theme: "celestial" },
  },

  // ------------------------------------------------------------------
  // 2. AVATAR FRAMES
  // ------------------------------------------------------------------
  {
    id: "frame_avatar_silver",
    category: "avatar_frame",
    name: "Silver Core Ring",
    description: "Sleek brushed aluminum circular avatar frame.",
    asset_url: "/assets/frames/avatar_silver.svg",
    preview_url: "/assets/frames/avatar_silver.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { theme: "silver" },
  },
  {
    id: "frame_avatar_violet",
    category: "avatar_frame",
    name: "Violet Arc Reactor",
    description: "Charged electro-plasma avatar frame with lightning prongs.",
    asset_url: "/assets/frames/avatar_violet.svg",
    preview_url: "/assets/frames/avatar_violet.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "violet" },
  },
  {
    id: "frame_avatar_flame",
    category: "avatar_frame",
    name: "Solar Corona Ring",
    description: "Blazing solar crest avatar frame with golden rays.",
    asset_url: "/assets/frames/avatar_flame.svg",
    preview_url: "/assets/frames/avatar_flame.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { theme: "flame" },
  },
  {
    id: "frame_avatar_quantum",
    category: "avatar_frame",
    name: "Quantum Cyber Halo",
    description: "Rotating holographic glyphs surrounding the avatar.",
    asset_url: "/assets/frames/avatar_quantum.svg",
    preview_url: "/assets/frames/avatar_quantum.svg",
    unlock_type: "level",
    unlock_req: { level: 30 },
    is_starter: false,
    rarity: "epic",
    metadata: { theme: "quantum" },
  },
  {
    id: "frame_avatar_crown",
    category: "avatar_frame",
    name: "Imperial Crown of ENOS",
    description: "Ornate crystalline crown for veteran guild champions.",
    asset_url: "/assets/frames/avatar_crown.svg",
    preview_url: "/assets/frames/avatar_crown.svg",
    unlock_type: "level",
    unlock_req: { level: 75 },
    is_starter: false,
    rarity: "legendary",
    metadata: { theme: "imperial" },
  },

  // ------------------------------------------------------------------
  // 3. THEME LAYERS (Multi-Layer Background Stack)
  // ------------------------------------------------------------------
  // Silver Theme
  {
    id: "theme_silver_base",
    category: "theme_layer",
    name: "Silver Carbon Base",
    description: "Deep slate carbon weave background layer.",
    asset_url: "/assets/themes/silver_base.svg",
    preview_url: "/assets/themes/silver_base.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { slot: "base", theme: "silver" },
  },
  {
    id: "theme_silver_circuit",
    category: "theme_layer",
    name: "Silver Cyber Circuit",
    description: "Subtle laser-etched metallic circuit network.",
    asset_url: "/assets/themes/silver_circuit.svg",
    preview_url: "/assets/themes/silver_circuit.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { slot: "overlay", theme: "silver" },
  },
  {
    id: "theme_silver_vignette",
    category: "theme_layer",
    name: "Silver Dark Vignette",
    description: "Deep edge shadows with subtle top chrome sheen.",
    asset_url: "/assets/themes/silver_vignette.svg",
    preview_url: "/assets/themes/silver_vignette.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { slot: "ambient", theme: "silver" },
  },

  // Electric Violet Theme
  {
    id: "theme_violet_base",
    category: "theme_layer",
    name: "Violet Void Base",
    description: "Dark purple nebula gradient with star dust.",
    asset_url: "/assets/themes/violet_base.svg",
    preview_url: "/assets/themes/violet_base.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "base", theme: "violet" },
  },
  {
    id: "theme_violet_lightning",
    category: "theme_layer",
    name: "Violet Lightning Lattice",
    description: "High-voltage electric lightning arcs and digital grids.",
    asset_url: "/assets/themes/violet_lightning.svg",
    preview_url: "/assets/themes/violet_lightning.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "overlay", theme: "violet" },
  },
  {
    id: "theme_violet_glow",
    category: "theme_layer",
    name: "Violet Plasma Aura",
    description: "Ambient ultraviolet glow radiating from center.",
    asset_url: "/assets/themes/violet_glow.svg",
    preview_url: "/assets/themes/violet_glow.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "ambient", theme: "violet" },
  },

  // Flaming Golden Orange Theme
  {
    id: "theme_flame_base",
    category: "theme_layer",
    name: "Solar Flare Base",
    description: "Deep volcanic obsidian with molten core underlay.",
    asset_url: "/assets/themes/flame_base.svg",
    preview_url: "/assets/themes/flame_base.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "base", theme: "flame" },
  },
  {
    id: "theme_flame_embers",
    category: "theme_layer",
    name: "Golden Embers & Flames",
    description: "Floating golden embers and stylized flame wisps.",
    asset_url: "/assets/themes/flame_embers.svg",
    preview_url: "/assets/themes/flame_embers.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "overlay", theme: "flame" },
  },
  {
    id: "theme_flame_radiance",
    category: "theme_layer",
    name: "Solar Radiance Burst",
    description: "Warm sunburst radiance overlay with ambient gold haze.",
    asset_url: "/assets/themes/flame_radiance.svg",
    preview_url: "/assets/themes/flame_radiance.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { slot: "ambient", theme: "flame" },
  },

  // ------------------------------------------------------------------
  // 4. LEVEL MILESTONE EMBLEMS
  // ------------------------------------------------------------------
  {
    id: "emblem_starter_silver",
    category: "emblem",
    name: "Initiate Crest (Lv 1)",
    description: "Standard Every Nation GG novice member crest.",
    asset_url: "/assets/emblems/emblem_lv1.svg",
    preview_url: "/assets/emblems/emblem_lv1.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { milestone_level: 1 },
  },
  {
    id: "emblem_milestone_20",
    category: "emblem",
    name: "Iron Vanguard (Lv 20)",
    description: "Forged iron crest awarded upon reaching Level 20.",
    asset_url: "/assets/emblems/emblem_lv20.svg",
    preview_url: "/assets/emblems/emblem_lv20.svg",
    unlock_type: "level",
    unlock_req: { level: 20 },
    is_starter: false,
    rarity: "rare",
    metadata: { milestone_level: 20 },
  },
  {
    id: "emblem_milestone_40",
    category: "emblem",
    name: "Silver Archon (Lv 40)",
    description: "Radiant silver twin-blade emblem for Level 40 veterans.",
    asset_url: "/assets/emblems/emblem_lv40.svg",
    preview_url: "/assets/emblems/emblem_lv40.svg",
    unlock_type: "level",
    unlock_req: { level: 40 },
    is_starter: false,
    rarity: "epic",
    metadata: { milestone_level: 40 },
  },
  {
    id: "emblem_milestone_60",
    category: "emblem",
    name: "Electrum Reaper (Lv 60)",
    description: "High-tier crest honoring master RPG raiders at Level 60.",
    asset_url: "/assets/emblems/emblem_lv60.svg",
    preview_url: "/assets/emblems/emblem_lv60.svg",
    unlock_type: "level",
    unlock_req: { level: 60 },
    is_starter: false,
    rarity: "legendary",
    metadata: { milestone_level: 60 },
  },
  {
    id: "emblem_milestone_80",
    category: "emblem",
    name: "Obsidian Paragon (Lv 80)",
    description: "Ancient obsidian monolith emblem for elite Level 80 titans.",
    asset_url: "/assets/emblems/emblem_lv80.svg",
    preview_url: "/assets/emblems/emblem_lv80.svg",
    unlock_type: "level",
    unlock_req: { level: 80 },
    is_starter: false,
    rarity: "legendary",
    metadata: { milestone_level: 80 },
  },
  {
    id: "emblem_milestone_100",
    category: "emblem",
    name: "Celestial Sovereign (Lv 100)",
    description: "Ultimate mythic emblem awarded upon achieving Level 100 mastery.",
    asset_url: "/assets/emblems/emblem_lv100.svg",
    preview_url: "/assets/emblems/emblem_lv100.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { milestone_level: 100 },
  },

  // ------------------------------------------------------------------
  // 5. TITLES & TITLE FRAMES
  // ------------------------------------------------------------------
  {
    id: "title_vault_pioneer",
    category: "title",
    name: "VAULT PIONEER",
    description: "Honoring founding participants of the EN Vault.",
    asset_url: "/assets/titles/title_pioneer.svg",
    preview_url: "/assets/titles/title_pioneer.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { title_text: "VAULT PIONEER" },
  },
  {
    id: "title_neo_vanguard",
    category: "title",
    name: "NEO VANGUARD",
    description: "Cybernetic vanguard title of Every Nation GG.",
    asset_url: "/assets/titles/title_vanguard.svg",
    preview_url: "/assets/titles/title_vanguard.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { title_text: "NEO VANGUARD" },
  },
  {
    id: "title_apex_raider",
    category: "title",
    name: "APEX RAIDER",
    description: "Title forged in the fires of weekly World Boss battles.",
    asset_url: "/assets/titles/title_raider.svg",
    preview_url: "/assets/titles/title_raider.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "boss_veteran" },
    is_starter: false,
    rarity: "rare",
    metadata: { title_text: "APEX RAIDER" },
  },
  {
    id: "title_celestial_archon",
    category: "title",
    name: "CELESTIAL ARCHON",
    description: "Supreme honorary title for dedicated community leaders.",
    asset_url: "/assets/titles/title_archon.svg",
    preview_url: "/assets/titles/title_archon.svg",
    unlock_type: "level",
    unlock_req: { level: 80 },
    is_starter: false,
    rarity: "legendary",
    metadata: { title_text: "CELESTIAL ARCHON" },
  },
  {
    id: "title_eternal_sovereign",
    category: "title",
    name: "ETERNAL SOVEREIGN",
    description: "The pinnacle title reserved for Level 100 achievers.",
    asset_url: "/assets/titles/title_sovereign.svg",
    preview_url: "/assets/titles/title_sovereign.svg",
    unlock_type: "level",
    unlock_req: { level: 100 },
    is_starter: false,
    rarity: "mythic",
    metadata: { title_text: "ETERNAL SOVEREIGN" },
  },

  // ------------------------------------------------------------------
  // 6. ACHIEVEMENT SHOWCASE BADGES (5 Slots)
  // ------------------------------------------------------------------
  {
    id: "badge_boss_slayer",
    category: "badge",
    name: "World Boss Slayer",
    description: "Participated in weekly ENOS World Boss battles.",
    asset_url: "/assets/badges/badge_boss.svg",
    preview_url: "/assets/badges/badge_boss.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "skull" },
  },
  {
    id: "badge_vault_pioneer",
    category: "badge",
    name: "Vault Pioneer",
    description: "Active Vault Coin staking and community governance.",
    asset_url: "/assets/badges/badge_vault.svg",
    preview_url: "/assets/badges/badge_vault.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "common",
    metadata: { icon: "coins" },
  },
  {
    id: "badge_quest_master",
    category: "badge",
    name: "Quest Master",
    description: "Completed Daily Quests in Every Nation GG.",
    asset_url: "/assets/badges/badge_quest.svg",
    preview_url: "/assets/badges/badge_quest.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "compass" },
  },
  {
    id: "badge_trivia_sage",
    category: "badge",
    name: "Trivia Sage",
    description: "Proved intellect in Daily Community Trivia.",
    asset_url: "/assets/badges/badge_trivia.svg",
    preview_url: "/assets/badges/badge_trivia.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "rare",
    metadata: { icon: "brain" },
  },
  {
    id: "badge_guild_champion",
    category: "badge",
    name: "Guild Champion",
    description: "Top contributor in Every Nation GG seasonal leaderboards.",
    asset_url: "/assets/badges/badge_guild.svg",
    preview_url: "/assets/badges/badge_guild.svg",
    unlock_type: "starter",
    unlock_req: {},
    is_starter: true,
    rarity: "epic",
    metadata: { icon: "trophy" },
  },
  {
    id: "badge_ap_conqueror",
    category: "badge",
    name: "AP Conqueror",
    description: "Maxed out weekly action points 20 weeks in a row.",
    asset_url: "/assets/badges/badge_conqueror.svg",
    preview_url: "/assets/badges/badge_conqueror.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "ap_20" },
    is_starter: false,
    rarity: "legendary",
    metadata: { icon: "zap" },
  },
  {
    id: "badge_flawless_streak",
    category: "badge",
    name: "Flawless 365 Streak",
    description: "Maintained daily community check-ins for 365 days.",
    asset_url: "/assets/badges/badge_streak.svg",
    preview_url: "/assets/badges/badge_streak.svg",
    unlock_type: "achievement",
    unlock_req: { achievement_id: "streak_365" },
    is_starter: false,
    rarity: "mythic",
    metadata: { icon: "flame" },
  },
];

// Helper methods
export function getAssetById(id: string): ProfileAsset | undefined {
  return ASSET_CATALOG.find((a) => a.id === id);
}

export function getAssetsByCategory(category: ProfileAsset["category"]): ProfileAsset[] {
  return ASSET_CATALOG.filter((a) => a.category === category);
}

export function getStarterAssets(): ProfileAsset[] {
  return ASSET_CATALOG.filter((a) => a.is_starter);
}

// 3 Curated Starter Preset Identities
export const STARTER_IDENTITIES = {
  silver: {
    id: "silver",
    name: "Silver Vanguard",
    description: "Clean brushed aluminum and sleek chrome aesthetics.",
    colorAccent: "#E2E8F0",
    nameColor: "#F8FAFC",
    nameFont: "Rajdhani",
    titleId: "title_vault_pioneer",
    titleColor: "#94A3B8",
    emblemId: "emblem_starter_silver",
    emblemColor: "#E2E8F0",
    avatarFrameId: "frame_avatar_silver",
    cardFrameId: "frame_card_silver",
    themeLayers: [
      "theme_silver_base",
      "theme_silver_circuit",
      "theme_silver_vignette",
    ],
    coinColor: "#F59E0B",
    achievementSlots: [
      "badge_boss_slayer",
      "badge_vault_pioneer",
      "badge_quest_master",
      "badge_trivia_sage",
      "badge_guild_champion",
    ],
  },
  violet: {
    id: "violet",
    name: "Electric Violet",
    description: "High-voltage neon violet and cyber-plasma aesthetics.",
    colorAccent: "#A855F7",
    nameColor: "#F3E8FF",
    nameFont: "Orbitron",
    titleId: "title_neo_vanguard",
    titleColor: "#C084FC",
    emblemId: "emblem_starter_silver",
    emblemColor: "#C084FC",
    avatarFrameId: "frame_avatar_violet",
    cardFrameId: "frame_card_violet",
    themeLayers: [
      "theme_violet_base",
      "theme_violet_lightning",
      "theme_violet_glow",
    ],
    coinColor: "#E879F9",
    achievementSlots: [
      "badge_boss_slayer",
      "badge_quest_master",
      "badge_guild_champion",
      "badge_vault_pioneer",
      "badge_trivia_sage",
    ],
  },
  flame: {
    id: "flame",
    name: "Flaming Golden Orange",
    description: "Radiant solar-forged gold and volcanic ember radiance.",
    colorAccent: "#F59E0B",
    nameColor: "#FEF3C7",
    nameFont: "Cinzel",
    titleId: "title_vault_pioneer",
    titleColor: "#FBBF24",
    emblemId: "emblem_starter_silver",
    emblemColor: "#F59E0B",
    avatarFrameId: "frame_avatar_flame",
    cardFrameId: "frame_card_flame",
    themeLayers: [
      "theme_flame_base",
      "theme_flame_embers",
      "theme_flame_radiance",
    ],
    coinColor: "#F59E0B",
    achievementSlots: [
      "badge_guild_champion",
      "badge_boss_slayer",
      "badge_vault_pioneer",
      "badge_quest_master",
      "badge_trivia_sage",
    ],
  },
};

// Available Curated Typography
export const AVAILABLE_FONTS = [
  { id: "Rajdhani", name: "Rajdhani (Cyber / Tactical)", category: "sans-serif" },
  { id: "Cinzel", name: "Cinzel (Royal / Epic)", category: "serif" },
  { id: "Orbitron", name: "Orbitron (Futuristic / Sci-Fi)", category: "display" },
  { id: "Outfit", name: "Outfit (Modern / Clean)", category: "sans-serif" },
  { id: "Montserrat", name: "Montserrat (Geometric / Bold)", category: "sans-serif" },
  { id: "Exo 2", name: "Exo 2 (High-Tech)", category: "sans-serif" },
  { id: "Inter", name: "Inter (Neutral / Sleek)", category: "sans-serif" },
];

// Curated Luxury Color Swatches
export const CURATED_COLOR_SWATCHES = [
  { hex: "#F8FAFC", label: "Pure Platinum" },
  { hex: "#38BDF8", label: "Aero Cyan" },
  { hex: "#818CF8", label: "Hyper Indigo" },
  { hex: "#A855F7", label: "Electric Violet" },
  { hex: "#EC4899", label: "Neon Magenta" },
  { hex: "#F43F5E", label: "Crimson Blaze" },
  { hex: "#F59E0B", label: "Imperial Gold" },
  { hex: "#10B981", label: "Emerald Matrix" },
  { hex: "#14B8A6", label: "Teal Lumina" },
  { hex: "#94A3B8", label: "Slate Steel" },
];

// Initial Demo/Mock Profiles for visual testing
export const DEMO_PROFILES: Record<string, UserProfileState> = {
  veteran: {
    userId: "891234567890123456",
    guildId: "123456789012345678",
    discordUsername: "everynation_ace",
    discordDisplayName: "Ace [EN Vanguard]",
    discordAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    profileExp: 84250, // Level 30+ (~1 Year active)
    profileLevel: 30,
    vaultCoins: 14250,
    equipped: {
      nameFont: "Rajdhani",
      nameColor: "#38BDF8",
      titleId: "title_vault_pioneer",
      titleColor: "#38BDF8",
      emblemId: "emblem_milestone_20",
      emblemColor: "#F59E0B",
      avatarFrameId: "frame_avatar_silver",
      cardFrameId: "frame_card_silver",
      themeLayers: [
        "theme_silver_base",
        "theme_silver_circuit",
        "theme_silver_vignette",
      ],
      coinColor: "#F59E0B",
      achievementSlots: [
        "badge_boss_slayer",
        "badge_guild_champion",
        "badge_vault_pioneer",
        "badge_quest_master",
        "badge_trivia_sage",
      ],
    },
    unlockedAssetIds: ASSET_CATALOG.filter(
      (a) => a.is_starter || (a.unlock_req.level && a.unlock_req.level <= 30)
    ).map((a) => a.id),
  },
  raider_violet: {
    userId: "782345678901234567",
    guildId: "123456789012345678",
    discordUsername: "cyber_valkyrie",
    discordDisplayName: "⚡ Valkyrie ⚡",
    discordAvatarUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=400&q=80",
    profileExp: 168000, // Level 52
    profileLevel: 52,
    vaultCoins: 28900,
    equipped: {
      nameFont: "Orbitron",
      nameColor: "#F3E8FF",
      titleId: "title_neo_vanguard",
      titleColor: "#C084FC",
      emblemId: "emblem_milestone_40",
      emblemColor: "#C084FC",
      avatarFrameId: "frame_avatar_violet",
      cardFrameId: "frame_card_violet",
      themeLayers: [
        "theme_violet_base",
        "theme_violet_lightning",
        "theme_violet_glow",
      ],
      coinColor: "#E879F9",
      achievementSlots: [
        "badge_boss_slayer",
        "badge_ap_conqueror",
        "badge_guild_champion",
        "badge_quest_master",
        "badge_vault_pioneer",
      ],
    },
    unlockedAssetIds: ASSET_CATALOG.filter(
      (a) => a.is_starter || (a.unlock_req.level && a.unlock_req.level <= 52) || a.id === "badge_ap_conqueror"
    ).map((a) => a.id),
  },
  mythic_sovereign: {
    userId: "993456789012345678",
    guildId: "123456789012345678",
    discordUsername: "sol_invictus",
    discordDisplayName: "✦ Sol Invictus ✦",
    discordAvatarUrl: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=400&q=80",
    profileExp: 417143, // Level 100 (Max Master)
    profileLevel: 100,
    vaultCoins: 99999,
    equipped: {
      nameFont: "Cinzel",
      nameColor: "#FEF3C7",
      titleId: "title_eternal_sovereign",
      titleColor: "#F59E0B",
      emblemId: "emblem_milestone_100",
      emblemColor: "#E0E7FF",
      avatarFrameId: "frame_avatar_crown",
      cardFrameId: "frame_card_celestial",
      themeLayers: [
        "theme_flame_base",
        "theme_flame_embers",
        "theme_flame_radiance",
      ],
      coinColor: "#F59E0B",
      achievementSlots: [
        "badge_flawless_streak",
        "badge_guild_champion",
        "badge_ap_conqueror",
        "badge_boss_slayer",
        "badge_vault_pioneer",
      ],
    },
    unlockedAssetIds: ASSET_CATALOG.map((a) => a.id),
  },
};
